variables:
    # Do not checkout the branch to merge, because we will merge it to the
    # target branch in the script below before running the tests
    GIT_CHECKOUT: "false"
    # Use clone strategy to always ensure clean state (solves issue with
    # remains after merge conflict)
    GIT_STRATEGY: "clone"

before_script:
    # Install git on our alpine base runner
    - apk update
    - apk add git
    - git config --global user.email "gitlab-runner@example.com"
    - git config --global user.name "GitLab Runner"

test:
    only:
        - merge_requests
    script:
        - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - git checkout -B $CI_MERGE_REQUEST_TARGET_BRANCH_NAME origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - git merge $CI_COMMIT_SHA
        - ./build/tests/shell_tst
